import requests
import json
import time
import uuid

# Configuration
RESOURCE_URL = "http://localhost:8003/resource"
ORCHESTRATOR_URL = "http://localhost:8001/orchestrator"

def create_test_scenario():
    print("--- Creating Test Scenario ---")
    scenario_id = str(uuid.uuid4())
    
    # Define Nodes
    nodes = [
        {
            "id": "node_start",
            "type": "start",
            "position": {"x": 0, "y": 0},
            "data": {"label": "Start", "category": "start"}
        },
        {
            "id": "node_persona",
            "type": "customNode",
            "position": {"x": 0, "y": 100},
            "data": {
                "label": "Angry Customer",
                "category": "persona",
                "role": "Customer",
                "prompt": "You are an angry customer complaining about a late delivery. You want a refund."
            }
        },
        {
            "id": "node_task_1",
            "type": "customNode",
            "position": {"x": 0, "y": 200},
            "data": {
                "label": "Complain",
                "category": "task",
                "instruction": "Complain about the late delivery and demand a refund."
            }
        },
        {
            "id": "node_expect_1",
            "type": "customNode",
            "position": {"x": 0, "y": 300},
            "data": {
                "label": "Check Apology",
                "category": "expectation",
                "criteria": "The agent should apologize for the delay."
            }
        },
        {
            "id": "node_end",
            "type": "customNode", # ReactFlow type
            "position": {"x": 0, "y": 400},
            "data": {"label": "End", "category": "end"}
        }
    ]
    
    # Define Edges
    edges = [
        {"id": "e1", "source": "node_start", "target": "node_persona"},
        {"id": "e2", "source": "node_persona", "target": "node_task_1"},
        {"id": "e3", "source": "node_task_1", "target": "node_expect_1"},
        {"id": "e4", "source": "node_expect_1", "target": "node_end"}
    ]
    
    payload = {
        "name": f"E2E Test Scenario {scenario_id[:8]}",
        "description": "Generated by verify_scenario.py",
        "nodes": nodes,
        "edges": edges,
        "agent_id": "mock-agent-id" # We might need a real agent ID but for now mock it
    }
    
    # We use a PUT/POST to create. Schema expects 'nodes' and 'edges'.
    # Note: Backend might require Agent ID to be valid.
    # Let's hope validation is loose or we have a seed agent.
    
    try:
        resp = requests.post(f"{RESOURCE_URL}/scenarios", json=payload)
        if resp.status_code in [200, 201]:
            data = resp.json()
            s_id = data.get("id")
            print(f"Scenario Created: {s_id}")
            return s_id
        else:
            print(f"Failed to create scenario: {resp.status_code} - {resp.text}")
            return None
    except Exception as e:
        print(f"Connection Error: {e}")
        return None

def trigger_campaign(scenario_id):
    print(f"\n--- Triggering Campaign for {scenario_id} ---")
    payload = {
        "scenario_id": scenario_id,
        "metadata": {
            "created_by": "verify_script",
            "source": "e2e_test"
        }
    }
    
    try:
        resp = requests.post(f"{ORCHESTRATOR_URL}/campaigns", json=payload)
        if resp.status_code in [200, 201]:
            data = resp.json()
            c_id = data.get("campaign_id")
            print(f"Campaign Started: {c_id}")
            return c_id
        else:
            print(f"Failed to start campaign: {resp.status_code} - {resp.text}")
            return None
    except Exception as e:
        print(f"Connection Error: {e}")
        return None

def poll_campaign(campaign_id):
    print(f"\n--- Polling Campaign {campaign_id} ---")
    
    for i in range(20): # Poll for 20 seconds
        try:
            resp = requests.get(f"{ORCHESTRATOR_URL}/campaigns/{campaign_id}/state")
            if resp.status_code == 200:
                data = resp.json()
                status = data.get("status")
                step = data.get("step")
                
                print(f"[{i}s] Status: {status} | Step: {step}")
                
                if status in ["completed", "failed", "error"]:
                    print("\n--- Campaign Finished ---")
                    print(json.dumps(data, indent=2))
                    return
            else:
                print(f"[{i}s] Error polling: {resp.status_code}")
                
            time.sleep(1)
        except Exception as e:
             print(f"Polling Exception: {e}")
             time.sleep(1)

if __name__ == "__main__":
    sid = create_test_scenario()
    if sid:
        cid = trigger_campaign(sid)
        if cid:
            poll_campaign(cid)

